name: yuv_to_png
description: "A plugin to convert YUV image data into PNG image format."
version: 1.0.0
homepage: "https://github.com/khaled45690/yuv_to_png"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  camera: ^0.11.3
  path_provider: ^2.1.2

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  plugin:
    platforms:
      android:
        package: com.khaled.yuv_to_png
        pluginClass: YuvToPngPlugin
        ffiPlugin: true

